[package]
name = "maldetete"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
reqwest = "0.11.22"
russh = "0.39.0"
russh-keys = "0.38.0"
systemctl = "0.3.1"
tokio = { version = "1.33.0", features = ["full"] }
